[build]
  functions = "netlify/functions-build" # Specify the output directory for built functions

[dev]
  # Optional: Specify the source folder for local development
  functions = "netlify/functions" 
